"""Dishes model

Revision ID: 91ec13070bfd
Revises: 5279383e94d5
Create Date: 2024-06-16 19:24:21.197782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ec13070bfd'
down_revision: Union[str, None] = '5279383e94d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('dish', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['Users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dishes')
    # ### end Alembic commands ###
